#!/usr/bin/env python3
"""Emit tech-stack-catalog.js (ES module) for the standalone composer. Run from repo root optional."""
from __future__ import annotations

import json
from pathlib import Path

# Canonical domain ids (must match project_service.TECH_STACK_DOMAINS)
DOMAINS = {
    "AWS": {
        "icon": "☁️",
        "accent": "#FF9900",
        "categories": {
            "Compute": [
                "AWS Lambda",
                "Amazon ECS",
                "Amazon ECS Fargate",
                "Amazon EKS",
                "Amazon EC2",
                "AWS App Runner",
                "AWS Batch",
                "Amazon Lightsail",
            ],
            "Storage": ["Amazon S3", "Amazon EBS", "Amazon EFS", "Amazon S3 Glacier", "AWS Backup"],
            "Database": [
                "Amazon RDS",
                "Amazon Aurora",
                "Amazon DynamoDB",
                "DynamoDB Streams",
                "Amazon ElastiCache (Redis)",
                "Amazon MemoryDB",
                "Amazon DocumentDB",
                "Amazon Neptune",
                "Amazon Timestream",
            ],
            "Networking & Content": [
                "Amazon VPC",
                "Amazon CloudFront",
                "Amazon Route 53",
                "Elastic Load Balancing",
                "AWS API Gateway",
                "AWS PrivateLink",
                "AWS Transit Gateway",
                "NAT Gateway",
                "AWS Global Accelerator",
            ],
            "Messaging & Integration": [
                "Amazon SQS",
                "Amazon SNS",
                "Amazon EventBridge",
                "AWS Step Functions",
                "Amazon MQ",
                "Amazon Kinesis Data Streams",
                "Amazon Kinesis Data Firehose",
                "AWS AppSync",
            ],
            "Security & Identity": [
                "AWS IAM",
                "AWS IAM Identity Center",
                "Amazon Cognito",
                "AWS KMS",
                "AWS Secrets Manager",
                "AWS Certificate Manager",
                "AWS WAF",
                "AWS Shield",
                "Amazon GuardDuty",
                "AWS Security Hub",
                "Amazon Inspector",
            ],
            "Observability & Management": [
                "Amazon CloudWatch",
                "AWS CloudTrail",
                "AWS X-Ray",
                "AWS Config",
                "AWS Systems Manager",
                "AWS Organizations",
                "AWS Control Tower",
                "AWS Trusted Advisor",
            ],
            "Analytics & AI": [
                "Amazon Athena",
                "Amazon QuickSight",
                "AWS Glue",
                "Amazon Redshift",
                "Amazon OpenSearch",
                "Amazon Bedrock",
                "Amazon SageMaker",
                "Amazon Comprehend",
                "Amazon Textract",
                "Amazon Rekognition",
            ],
            "CI/CD & Developer Tools": [
                "AWS CodePipeline",
                "AWS CodeBuild",
                "AWS CodeDeploy",
                "Amazon ECR",
                "AWS CloudFormation",
                "AWS CDK",
            ],
            "Cost & FinOps": [
                "AWS Cost Explorer",
                "AWS Budgets",
                "Cost & Usage Reports",
                "Savings Plans",
                "Reserved Instances",
                "AWS Cost Anomaly Detection",
            ],
        },
    },
    "FastAPI": {
        "icon": "⚡",
        "accent": "#009688",
        "categories": {
            "Web Frameworks & Servers": [
                "FastAPI",
                "Flask",
                "Django",
                "Litestar",
                "Uvicorn",
                "Gunicorn",
                "Hypercorn",
            ],
            "Data Validation": ["Pydantic", "Marshmallow", "attrs", "msgspec"],
            "ORM & Database Access": [
                "SQLAlchemy",
                "SQLModel",
                "Tortoise ORM",
                "Prisma Client Python",
                "asyncpg",
                "psycopg2",
                "databases",
                "aiosqlite",
            ],
            "Migrations": ["Alembic", "Django Migrations", "yoyo-migrations"],
            "Auth & Authorization": [
                "python-jose",
                "PyJWT",
                "Authlib",
                "passlib",
                "bcrypt",
                "Supabase Auth SDK",
                "python-multipart",
            ],
            "Task Queues & Jobs": [
                "Celery",
                "Dramatiq",
                "Huey",
                "ARQ",
                "RQ (Redis Queue)",
                "FastAPI BackgroundTasks",
            ],
            "Caching": ["Redis (redis-py)", "aioredis", "cachetools", "diskcache"],
            "API Docs & Contracts": ["Swagger/OpenAPI", "ReDoc", "Stoplight", "Spectral"],
            "HTTP Clients": ["httpx", "aiohttp", "requests", "urllib3"],
            "File & Storage": ["boto3 (S3)", "Pillow", "python-magic"],
            "Scheduling": ["APScheduler", "Celery Beat", "cron"],
            "Testing": [
                "pytest",
                "pytest-asyncio",
                "httpx (test client)",
                "factory_boy",
                "Faker",
                "hypothesis",
                "coverage",
                "tox",
            ],
            "Code Quality": ["Ruff", "Black", "isort", "mypy", "pylint", "bandit", "flake8"],
            "Logging & Observability": [
                "structlog",
                "loguru",
                "python-json-logger",
                "OpenTelemetry",
                "Sentry SDK",
            ],
            "Configuration": ["pydantic-settings", "python-dotenv", "dynaconf", "environs"],
            "WebSockets & Realtime": ["websockets", "python-socketio", "Broadcaster"],
            "CLI & Scripting": ["Typer", "Click", "Rich", "tqdm"],
        },
    },
    "Frontend UI": {
        "icon": "🎨",
        "accent": "#E91E63",
        "categories": {
            "Frameworks": [
                "React",
                "Next.js",
                "Vue",
                "Nuxt",
                "Svelte",
                "SvelteKit",
                "Angular",
                "Astro",
                "Remix",
                "Solid.js",
            ],
            "State Management": [
                "Zustand",
                "Redux Toolkit",
                "Jotai",
                "Recoil",
                "Pinia",
                "MobX",
                "XState",
                "Valtio",
            ],
            "Data Fetching": ["TanStack Query", "SWR", "Apollo Client", "URQL", "Axios", "ky", "ofetch"],
            "Styling & CSS": [
                "Tailwind CSS",
                "CSS Modules",
                "styled-components",
                "Emotion",
                "Sass/SCSS",
                "Vanilla Extract",
                "UnoCSS",
                "PostCSS",
            ],
            "Component Libraries": [
                "shadcn/ui",
                "Radix UI",
                "Headless UI",
                "Material UI",
                "Ant Design",
                "Chakra UI",
                "Mantine",
                "DaisyUI",
                "Flowbite",
            ],
            "Build Tools": ["Vite", "Webpack", "Turbopack", "esbuild", "SWC", "Parcel", "Rollup"],
            "Testing": ["Vitest", "Jest", "Playwright", "Cypress", "Testing Library", "Storybook", "Chromatic", "MSW"],
            "Forms & Validation": ["React Hook Form", "Formik", "Zod", "Yup", "Valibot", "VeeValidate"],
            "Animation & Motion": ["Framer Motion", "GSAP", "Lottie", "AutoAnimate", "Motion One"],
            "Charts & Visualization": [
                "Recharts",
                "Chart.js",
                "D3.js",
                "Nivo",
                "Victory",
                "Tremor",
                "Apache ECharts",
                "Plotly",
            ],
            "Date & Time": ["date-fns", "Day.js", "Luxon", "Temporal API"],
            "Internationalization": ["react-i18next", "next-intl", "vue-i18n", "FormatJS", "Lingui"],
            "Icons & Assets": ["Lucide", "Heroicons", "Phosphor", "React Icons", "SVG sprites"],
            "Maps & Geospatial": ["Mapbox GL", "Leaflet", "Google Maps API", "Deck.gl"],
            "Rich Text & Editors": ["TipTap", "ProseMirror", "Slate", "Lexical", "Monaco Editor", "CodeMirror"],
            "Drag & Drop": ["dnd-kit", "react-beautiful-dnd", "SortableJS"],
            "Tables & Grids": ["TanStack Table", "AG Grid", "react-data-grid"],
            "Notifications": ["Sonner", "react-hot-toast", "Notistack"],
            "Auth & Session": ["NextAuth.js", "Clerk", "Supabase Auth", "Auth0 SDK", "Firebase Auth"],
            "Mobile & PWA": ["React Native", "Expo", "Capacitor", "PWA APIs"],
            "Accessibility": ["axe-core", "pa11y", "Lighthouse", "WAVE"],
        },
    },
    "Database": {
        "icon": "🗄️",
        "accent": "#2196F3",
        "categories": {
            "Relational": [
                "PostgreSQL",
                "MySQL",
                "MariaDB",
                "SQLite",
                "CockroachDB",
                "PlanetScale",
                "Neon",
                "Supabase (Postgres)",
            ],
            "Document": ["MongoDB", "Amazon DocumentDB", "CouchDB", "FerretDB"],
            "Key-Value": ["Redis", "Amazon DynamoDB", "Valkey", "KeyDB", "etcd"],
            "Wide Column": ["Apache Cassandra", "ScyllaDB", "Amazon Keyspaces"],
            "Graph": ["Neo4j", "Amazon Neptune", "ArangoDB", "Dgraph"],
            "Time Series": ["TimescaleDB", "InfluxDB", "Amazon Timestream", "QuestDB"],
            "Search Engines": ["Elasticsearch", "OpenSearch", "Meilisearch", "Typesense", "Algolia"],
            "Vector Databases": ["Pinecone", "Weaviate", "Qdrant", "Chroma", "pgvector", "Milvus"],
            "Message Brokers": [
                "Apache Kafka",
                "RabbitMQ",
                "Amazon SQS",
                "Amazon SNS",
                "NATS",
                "Redis Streams",
            ],
            "Caching": ["Redis", "Memcached", "Varnish", "CDN caching"],
            "ORMs & Query Builders": [
                "SQLAlchemy",
                "Prisma",
                "TypeORM",
                "Drizzle",
                "Knex.js",
                "Sequelize",
                "Django ORM",
                "Peewee",
            ],
            "Migration Tools": ["Alembic", "Flyway", "Liquibase", "Atlas", "Prisma Migrate", "golang-migrate"],
            "Admin & Management": ["pgAdmin", "DBeaver", "DataGrip", "TablePlus", "Adminer", "Supabase Studio"],
            "Connection Pooling": ["PgBouncer", "pgpool-II", "ProxySQL", "RDS Proxy"],
            "Backup & Replication": ["pg_dump", "pg_basebackup", "Barman", "WAL-G", "Logical Replication"],
        },
    },
    "Data Analytics": {
        "icon": "📊",
        "accent": "#9C27B0",
        "categories": {
            "Dataframe & Processing": ["Pandas", "Polars", "Dask", "Modin", "Vaex", "PySpark", "DuckDB"],
            "Numerical & Scientific": ["NumPy", "SciPy", "scikit-learn", "statsmodels", "SymPy"],
            "Visualization": ["Matplotlib", "Seaborn", "Plotly", "Altair", "Bokeh", "Folium", "Plotnine"],
            "BI & Dashboards": [
                "Apache Superset",
                "Metabase",
                "Grafana",
                "Amazon QuickSight",
                "Tableau",
                "Power BI",
                "Streamlit",
                "Gradio",
            ],
            "Notebooks": ["Jupyter", "JupyterLab", "Google Colab", "VS Code Notebooks", "Databricks Notebooks", "Observable"],
            "Orchestration & Pipelines": [
                "Apache Airflow",
                "Prefect",
                "Dagster",
                "Luigi",
                "Mage.ai",
                "AWS Step Functions",
                "dbt",
            ],
            "ETL & Integration": ["dbt", "Airbyte", "Fivetran", "Singer", "AWS Glue", "Stitch"],
            "Feature Stores": ["Feast", "Tecton", "Hopsworks"],
            "Experiment Tracking": ["MLflow", "Weights & Biases", "Neptune.ai", "DVC", "ClearML", "Comet"],
            "Storage Formats": ["Parquet", "Apache Arrow", "ORC", "Avro", "CSV", "JSON", "HDF5", "Delta Lake", "Apache Iceberg"],
            "Data Quality": ["Great Expectations", "Soda", "Pandera", "dbt tests", "Deequ"],
            "Data Catalogs": ["DataHub", "Amundsen", "OpenMetadata", "AWS Glue Data Catalog"],
            "ML Frameworks": ["PyTorch", "TensorFlow", "Keras", "JAX", "Hugging Face Transformers", "LangChain", "LlamaIndex"],
            "ML Serving": ["BentoML", "Seldon Core", "TorchServe", "TF Serving", "ONNX Runtime", "vLLM", "Ollama"],
            "Profiling & EDA": ["ydata-profiling", "sweetviz", "D-Tale", "Lux"],
        },
    },
    "Software Dev": {
        "icon": "🛠️",
        "accent": "#4CAF50",
        "categories": {
            "Version Control": ["Git", "GitHub", "GitLab", "Bitbucket", "Azure DevOps"],
            "CI/CD": ["GitHub Actions", "GitLab CI", "Jenkins", "CircleCI", "Travis CI", "ArgoCD", "Flux", "Drone"],
            "Containerization": ["Docker", "Docker Compose", "Podman", "Colima", "BuildKit", "Kaniko"],
            "Container Orchestration": ["Kubernetes", "Amazon ECS", "Docker Swarm", "Nomad", "k3s"],
            "Infrastructure as Code": ["Terraform", "Pulumi", "AWS CDK", "CloudFormation", "Ansible", "Chef", "Puppet"],
            "IDEs & Editors": ["VS Code", "Cursor", "PyCharm", "WebStorm", "Neovim", "Zed", "IntelliJ IDEA"],
            "Dev Environments": ["DevContainers", "GitHub Codespaces", "Gitpod", "Vagrant", "Nix"],
            "Package Management": ["pip", "Poetry", "npm", "yarn", "pnpm", "Homebrew", "Cargo"],
            "API Development": ["Postman", "Insomnia", "Bruno", "HTTPie", "curl", "Hoppscotch", "Swagger Editor"],
            "Documentation": ["Obsidian", "Notion", "Confluence", "MkDocs", "Docusaurus", "GitBook"],
            "Project Management": ["Jira", "Linear", "Trello", "Asana", "GitHub Issues", "Shortcut", "Plane"],
            "Communication": ["Slack", "Discord", "Microsoft Teams", "Loom", "Zoom"],
            "Code Quality": ["ESLint", "Prettier", "Ruff", "Black", "SonarQube", "CodeClimate", "pre-commit"],
            "Security & Scanning": ["Snyk", "Dependabot", "Trivy", "Grype", "GitGuardian", "Semgrep", "OWASP ZAP"],
            "Secrets Management": ["dotenv", "AWS Secrets Manager", "HashiCorp Vault", "1Password CLI", "Doppler", "SOPS"],
            "Monitoring": ["Datadog", "Grafana", "Sentry", "New Relic", "PagerDuty", "OpsGenie", "Prometheus"],
            "Feature Flags": ["LaunchDarkly", "Unleash", "Flagsmith", "PostHog", "Flipt"],
            "Error Tracking": ["Sentry", "Bugsnag", "Rollbar", "Raygun"],
            "Design & Prototyping": ["Figma", "Sketch", "Adobe XD", "Storybook", "Zeroheight"],
            "Cloud Providers": ["AWS", "GCP", "Azure", "Vercel", "Netlify", "Fly.io", "Railway", "Render", "DigitalOcean", "Supabase", "Firebase"],
        },
    },
}

PRESETS = {
    "AWS": {
        "Serverless API": [
            "AWS Lambda",
            "AWS API Gateway",
            "Amazon DynamoDB",
            "Amazon CloudWatch",
            "AWS IAM",
            "AWS KMS",
            "Amazon S3",
        ],
        "Event-Driven": [
            "AWS Lambda",
            "Amazon SQS",
            "Amazon SNS",
            "Amazon EventBridge",
            "Amazon DynamoDB",
            "Amazon CloudWatch",
            "AWS X-Ray",
        ],
        "Container Platform": [
            "Amazon ECS Fargate",
            "Elastic Load Balancing",
            "Amazon ECR",
            "Amazon RDS",
            "Amazon CloudWatch",
            "AWS IAM",
            "Amazon VPC",
            "NAT Gateway",
        ],
        "Analytics Pipeline": [
            "Amazon S3",
            "Amazon Kinesis Data Firehose",
            "AWS Glue",
            "Amazon Athena",
            "Amazon QuickSight",
            "AWS IAM",
        ],
        "Static + API": [
            "Amazon S3",
            "Amazon CloudFront",
            "AWS API Gateway",
            "AWS Lambda",
            "Amazon DynamoDB",
            "Amazon Route 53",
            "AWS Certificate Manager",
        ],
        "Full SaaS Stack": [
            "Amazon ECS Fargate",
            "AWS API Gateway",
            "Amazon RDS",
            "Amazon ElastiCache (Redis)",
            "Amazon S3",
            "Amazon CloudFront",
            "Amazon SQS",
            "Amazon SNS",
            "Amazon EventBridge",
            "Amazon CloudWatch",
            "AWS X-Ray",
            "AWS IAM",
            "AWS KMS",
            "AWS Secrets Manager",
            "Amazon VPC",
            "NAT Gateway",
            "Amazon ECR",
            "AWS CodePipeline",
            "AWS Budgets",
        ],
        "AI/ML Platform": [
            "Amazon SageMaker",
            "Amazon Bedrock",
            "Amazon S3",
            "AWS Lambda",
            "Amazon DynamoDB",
            "Amazon CloudWatch",
            "AWS IAM",
            "Amazon ECR",
            "AWS Step Functions",
        ],
    },
    "FastAPI": {
        "Minimal API": ["FastAPI", "Uvicorn", "Pydantic", "python-dotenv"],
        "Production API": [
            "FastAPI",
            "Uvicorn",
            "Gunicorn",
            "Pydantic",
            "SQLAlchemy",
            "Alembic",
            "asyncpg",
            "pydantic-settings",
            "structlog",
            "pytest",
            "Ruff",
            "Black",
            "mypy",
        ],
        "Auth + RBAC": [
            "FastAPI",
            "Uvicorn",
            "Pydantic",
            "PyJWT",
            "passlib",
            "bcrypt",
            "SQLAlchemy",
            "Alembic",
            "python-multipart",
        ],
        "Async Workers": [
            "FastAPI",
            "Uvicorn",
            "Celery",
            "Redis (redis-py)",
            "Celery Beat",
            "APScheduler",
            "structlog",
            "pytest",
        ],
        "Full Stack API": [
            "FastAPI",
            "Uvicorn",
            "Gunicorn",
            "Pydantic",
            "SQLAlchemy",
            "SQLModel",
            "Alembic",
            "asyncpg",
            "PyJWT",
            "passlib",
            "bcrypt",
            "Celery",
            "Redis (redis-py)",
            "httpx",
            "boto3 (S3)",
            "pytest",
            "pytest-asyncio",
            "factory_boy",
            "Faker",
            "Ruff",
            "Black",
            "mypy",
            "structlog",
            "OpenTelemetry",
            "Sentry SDK",
            "pydantic-settings",
            "python-dotenv",
        ],
        "Supabase Backend": [
            "FastAPI",
            "Uvicorn",
            "Pydantic",
            "Supabase Auth SDK",
            "httpx",
            "pydantic-settings",
            "python-dotenv",
            "structlog",
            "pytest",
        ],
    },
    "Frontend UI": {
        "React Minimal": ["React", "Vite", "Tailwind CSS", "Zustand"],
        "Next.js Full": [
            "Next.js",
            "React",
            "Tailwind CSS",
            "shadcn/ui",
            "Radix UI",
            "Zustand",
            "TanStack Query",
            "Axios",
            "React Hook Form",
            "Zod",
            "Framer Motion",
            "Lucide",
            "Vitest",
            "Playwright",
            "Testing Library",
        ],
        "React Dashboard": [
            "React",
            "Vite",
            "Tailwind CSS",
            "shadcn/ui",
            "Zustand",
            "TanStack Query",
            "Axios",
            "Recharts",
            "TanStack Table",
            "React Hook Form",
            "Zod",
            "date-fns",
            "Lucide",
            "Sonner",
        ],
        "Mobile First": ["React Native", "Expo", "Zustand", "TanStack Query", "React Hook Form", "Zod"],
        "Design System": [
            "React",
            "Vite",
            "Tailwind CSS",
            "Radix UI",
            "Storybook",
            "Chromatic",
            "Framer Motion",
            "Lucide",
            "CSS Modules",
            "Vitest",
            "Testing Library",
            "axe-core",
        ],
        "Full Production": [
            "React",
            "Next.js",
            "Tailwind CSS",
            "shadcn/ui",
            "Radix UI",
            "Zustand",
            "TanStack Query",
            "Axios",
            "React Hook Form",
            "Zod",
            "Framer Motion",
            "Recharts",
            "date-fns",
            "react-i18next",
            "Lucide",
            "TipTap",
            "Sonner",
            "NextAuth.js",
            "Vite",
            "Vitest",
            "Playwright",
            "Testing Library",
            "Storybook",
            "MSW",
            "axe-core",
        ],
    },
    "Database": {
        "PostgreSQL Stack": ["PostgreSQL", "SQLAlchemy", "Alembic", "pgAdmin", "PgBouncer", "pg_dump"],
        "Supabase Stack": ["Supabase (Postgres)", "PostgreSQL", "Prisma", "Supabase Studio"],
        "Redis + Postgres": ["PostgreSQL", "Redis", "SQLAlchemy", "Alembic", "PgBouncer", "pgAdmin"],
        "Search + Relational": ["PostgreSQL", "Elasticsearch", "Redis", "SQLAlchemy", "Alembic", "PgBouncer"],
        "Multi-Model": [
            "PostgreSQL",
            "Redis",
            "MongoDB",
            "Elasticsearch",
            "SQLAlchemy",
            "Prisma",
            "Alembic",
            "pgAdmin",
            "DBeaver",
        ],
        "Analytics Ready": ["PostgreSQL", "Redis", "TimescaleDB", "pgvector", "SQLAlchemy", "Alembic", "DBeaver"],
        "Event Driven": ["PostgreSQL", "Redis", "Apache Kafka", "Redis Streams", "SQLAlchemy", "Alembic", "PgBouncer"],
    },
    "Data Analytics": {
        "Pandas Starter": ["Pandas", "NumPy", "Matplotlib", "Jupyter", "CSV"],
        "Full EDA": ["Pandas", "NumPy", "Matplotlib", "Seaborn", "Plotly", "JupyterLab", "ydata-profiling", "sweetviz"],
        "ML Pipeline": ["Pandas", "NumPy", "scikit-learn", "PyTorch", "MLflow", "DVC", "Jupyter", "Parquet", "Great Expectations"],
        "Data Engineering": [
            "PySpark",
            "Apache Airflow",
            "dbt",
            "Parquet",
            "Delta Lake",
            "Apache Arrow",
            "Great Expectations",
            "DataHub",
        ],
        "BI & Reporting": ["Pandas", "Plotly", "Apache Superset", "Metabase", "Streamlit", "Parquet", "dbt"],
        "LLM & AI": [
            "Pandas",
            "NumPy",
            "Hugging Face Transformers",
            "LangChain",
            "LlamaIndex",
            "PyTorch",
            "Weights & Biases",
            "JupyterLab",
            "Parquet",
        ],
        "Production Analytics": [
            "Polars",
            "Pandas",
            "NumPy",
            "scikit-learn",
            "Plotly",
            "Altair",
            "Apache Airflow",
            "dbt",
            "Parquet",
            "Apache Iceberg",
            "Great Expectations",
            "MLflow",
            "DataHub",
            "JupyterLab",
            "Streamlit",
        ],
    },
    "Software Dev": {
        "Solo Dev": ["Git", "GitHub", "VS Code", "Docker", "Docker Compose", "pip", "Poetry", "GitHub Actions", "dotenv", "Obsidian"],
        "Team Startup": [
            "Git",
            "GitHub",
            "VS Code",
            "Docker",
            "Docker Compose",
            "GitHub Actions",
            "Terraform",
            "pip",
            "Poetry",
            "npm",
            "Slack",
            "Linear",
            "Figma",
            "Sentry",
            "dotenv",
            "ESLint",
            "Prettier",
            "Ruff",
        ],
        "Full Platform": [
            "Git",
            "GitHub",
            "VS Code",
            "Cursor",
            "Docker",
            "Docker Compose",
            "Kubernetes",
            "Terraform",
            "GitHub Actions",
            "ArgoCD",
            "pip",
            "Poetry",
            "npm",
            "pnpm",
            "Slack",
            "Linear",
            "Figma",
            "Sentry",
            "Datadog",
            "PagerDuty",
            "Snyk",
            "Dependabot",
            "LaunchDarkly",
            "Obsidian",
            "1Password CLI",
            "ESLint",
            "Prettier",
            "Ruff",
            "Black",
            "pre-commit",
            "SonarQube",
            "Postman",
        ],
        "AWS Native": [
            "Git",
            "GitHub",
            "VS Code",
            "Docker",
            "Docker Compose",
            "Terraform",
            "GitHub Actions",
            "AWS",
            "pip",
            "Poetry",
            "npm",
            "Sentry",
            "dotenv",
            "ESLint",
            "Ruff",
        ],
        "Indie Hacker": [
            "Git",
            "GitHub",
            "VS Code",
            "Docker",
            "Vercel",
            "Supabase",
            "GitHub Actions",
            "npm",
            "pnpm",
            "dotenv",
            "Figma",
            "Obsidian",
            "Sentry",
        ],
        "Enterprise": [
            "Git",
            "GitHub",
            "VS Code",
            "Docker",
            "Docker Compose",
            "Kubernetes",
            "Terraform",
            "Ansible",
            "GitHub Actions",
            "ArgoCD",
            "pip",
            "Poetry",
            "npm",
            "pnpm",
            "Slack",
            "Microsoft Teams",
            "Jira",
            "Confluence",
            "Figma",
            "Datadog",
            "Grafana",
            "PagerDuty",
            "Sentry",
            "Snyk",
            "Dependabot",
            "Trivy",
            "GitGuardian",
            "Semgrep",
            "HashiCorp Vault",
            "1Password CLI",
            "LaunchDarkly",
            "SonarQube",
            "Postman",
            "pre-commit",
            "ESLint",
            "Prettier",
            "Ruff",
            "Black",
            "AWS",
            "GCP",
        ],
    },
}


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "assets" / "tech-stack-catalog.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    blob = json.dumps({"DOMAINS": DOMAINS, "PRESETS": PRESETS}, ensure_ascii=False)
    out.write_text(
        "// Auto-generated by scripts/emit_tech_stack_catalog.py\n"
        "export const CATALOG = "
        + blob
        + ";\n"
        "export const DOMAIN_ORDER = "
        + json.dumps(list(DOMAINS.keys()))
        + ";\n",
        encoding="utf-8",
    )
    print("wrote", out, "bytes", out.stat().st_size)


if __name__ == "__main__":
    main()
